GROUNDING_RESISTANCE = 1e-6
WIRE_RESISTANCE = 0.01
BARF = "=" * 50 + "\n"
BARE = "\n" + "=" * 50
RAWSPICE_ITERATIONS = 1e6
MPPT_BATTERY_VOLTAGE_BUFFER = 2.0
VOLTAGE_MISMATCH_TOLERANCE = 5.0
POWER_MISMATCH_TOLERANCE_PERCENTAGE = 1.0
EPSILON = 1e-12